[project]
name = "jax-gpt2-from-scratch"
version = "0.1.0"
description = "An implemention of the GPT-2 architecture using JAX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.12.7",
    "jax>=0.10.1",
    "optax>=0.2.8",
]


[project.optional-dependencies]
cuda13 = [
    "jax[cuda13]>=0.10.1",
]

