[project]
name = "jax-gpt2-from-scratch"
version = "0.1.0"
description = "An implemention of the GPT-2 architecture using JAX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.1",
    "flax>=0.12.7",
    "huggingface-hub>=1.17.0",
    "ipython>=9.14.0",
    "jax>=0.10.1",
    "matplotlib>=3.11.0",
    "optax>=0.2.8",
    "orbax>=0.1.9",
    "safetensors>=0.7.0",
    "tiktoken>=0.13.0",
]


[project.optional-dependencies]
cuda13 = [
    "jax[cuda13]>=0.10.1",
]

